version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "weekly"
    groups:
      all-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
