pipeline:
    install:
        - step: CreateVEnv
          module: pypeline.steps.create_venv
          config:
              bootstrap_script: .bootstrap/bootstrap.py
              python_executable: python313
              python_package_manager: poetry>=2.2
        - step: ScoopInstall
          module: pypeline.steps.scoop_install
        - step: GenerateEnvSetupScript
          module: pypeline.steps.env_setup_script

    lint:
        - step: PreCommit
          run: pre-commit run --all-files

    build:
        - step: RunPytest
          file: steps/build.py
        - step: GenerateDocs
          file: steps/build.py
