"""Sphinx extension that injects the SPL platform layout CSS.

Add ``"spl_core.report_generation.spl_theme_extension"`` to your Sphinx
``extensions`` list.  The extension automatically registers the static
directory and CSS file so that downstream projects don't need to manage
paths themselves.

It also bridges sphinx-needs' dark palette to the PyData Sphinx Theme dark-mode
toggle: sphinx-needs ships a ``dark.css`` keyed on ``:root`` (selected globally,
not on PyData's ``data-theme``), so its requirement blocks stay light when
PyData switches to dark. We re-scope that palette to ``html[data-theme="dark"]``
at build time, reading the values straight from the installed sphinx-needs so
they cannot drift out of sync with hardcoded copies.

Report navigation (which pages appear per report type) is data-driven via the
project's Jinja templates (``index.md`` / ``doc/components/index.md`` rendered
with ``build_config``); it is intentionally NOT generated by this extension.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

from sphinx.application import Sphinx

_STATIC_DIR = str(Path(__file__).resolve().parent / "static")

_DARK_SELECTOR = 'html[data-theme="dark"]'


def setup(app: Sphinx) -> dict[str, Any]:
    """Register static assets with Sphinx."""
    app.connect("builder-inited", _add_static_assets)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}


def rescope_root_block(css_text: str, selector: str = _DARK_SELECTOR) -> str | None:
    """Re-scope the first ``:root { ... }`` variable block onto ``selector``.

    Returns ``None`` if no ``:root`` block is found. Custom-property declarations
    contain no braces, so the first ``}`` after ``:root {`` closes the block.
    """
    start = css_text.find(":root")
    if start == -1:
        return None
    brace_open = css_text.find("{", start)
    brace_close = css_text.find("}", brace_open) if brace_open != -1 else -1
    if brace_open == -1 or brace_close == -1:
        return None
    body = css_text[brace_open + 1 : brace_close].strip()
    return f"{selector} {{\n{body}\n}}\n"


def _generate_needs_dark_css() -> str | None:
    """Build CSS that maps sphinx-needs' dark palette to PyData dark mode.

    Reads the ``:root`` block from the installed sphinx-needs ``dark.css`` so the
    values stay in sync with the package. Returns ``None`` if sphinx-needs or its
    dark theme file is unavailable.
    """
    try:
        import sphinx_needs
    except ImportError:
        return None

    dark_css = Path(sphinx_needs.__file__).resolve().parent / "css" / "themes" / "dark.css"
    if not dark_css.is_file():
        return None

    rescoped = rescope_root_block(dark_css.read_text(encoding="utf-8"))
    if rescoped is None:
        return None
    header = "/* Generated from sphinx-needs dark.css by spl_theme_extension — do not edit. */\n"
    return header + rescoped


def _add_static_assets(app: Sphinx) -> None:
    """Append the package static dir, register CSS files, and set default logo."""
    if _STATIC_DIR not in app.config.html_static_path:
        app.config.html_static_path.append(_STATIC_DIR)
    app.add_css_file("spl_custom.css")

    # Re-scope sphinx-needs' dark palette to the PyData dark-mode toggle. Generated
    # into a temp dir (not the read-only package/source tree) and registered as a
    # static asset. Higher specificity than :root means load order is irrelevant.
    needs_dark_css = _generate_needs_dark_css()
    if needs_dark_css:
        generated_dir = Path(tempfile.mkdtemp(prefix="spl_theme_"))
        (generated_dir / "spl_needs_dark.css").write_text(needs_dark_css, encoding="utf-8")
        app.config.html_static_path.append(str(generated_dir))
        app.add_css_file("spl_needs_dark.css")

    # Set default logo if no project-level html_logo is configured
    if not app.config.html_logo:
        app.config.html_logo = str(Path(_STATIC_DIR) / "spl_core_logo.png")
