"""Generate Markdown coverage table from gcovr JSON with links to HTML detail pages.

This script reads a gcovr JSON file (trace or summary format) and produces
a Markdown table showing per-file coverage. When an HTML detail directory
is provided, file names become clickable links to the corresponding
gcovr HTML detail pages.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def _compute_line_coverage_from_trace(file_data: dict[str, Any]) -> tuple[int, int]:
    """Compute (covered, total) from gcovr trace format lines array."""
    lines = file_data.get("lines", [])
    total = len(lines)
    covered = sum(1 for line in lines if line.get("count", 0) > 0)
    return covered, total


def _compute_branch_coverage_from_trace(file_data: dict[str, Any]) -> tuple[int, int]:
    """Compute (covered, total) from gcovr trace format branches."""
    total = 0
    covered = 0
    for line in file_data.get("lines", []):
        for branch in line.get("branches", []):
            total += 1
            if branch.get("count", 0) > 0:
                covered += 1
    return covered, total


def _compute_condition_coverage_from_trace(file_data: dict[str, Any]) -> tuple[int, int]:
    """Compute (covered, total) from gcovr trace format conditions.

    Each condition entry has 'count' (total outcomes) and 'covered' (covered outcomes).
    This data is generated by GCC's -fcondition-coverage flag and is essential
    for MC/DC (Modified Condition/Decision Coverage) evidence in safety projects.
    """
    total = 0
    covered = 0
    for line in file_data.get("lines", []):
        for cond in line.get("conditions", []):
            total += cond.get("count", 0)
            covered += cond.get("covered", 0)
    return covered, total


_HASH_SUFFIX_RE = re.compile(r"\.[0-9a-f]{32}$")


def _find_detail_file(html_dir: Path, source_filename: str) -> str | None:
    """Find the HTML detail file for a source by scanning the output directory.

    gcovr names detail files differently across versions:
    - gcovr 7.x: ``<stem>.<encoded_path>.html`` where the encoded path
      replaces ``/`` and ``\\`` with ``.``
    - gcovr 8.x: ``<stem>.<source_basename>.<md5_hash>.html``

    Full encoded-path matches (gcovr 7.x) take priority over basename
    matches (gcovr 8.x) to avoid false positives when both formats exist.
    """
    if not html_dir.exists():
        return None
    encoded_full = source_filename.replace("/", ".").replace("\\", ".")
    encoded_base = Path(source_filename).name

    html_files = [f for f in sorted(html_dir.iterdir()) if f.is_file() and f.suffix == ".html" and f.name != "index.html"]

    # Pass 1: gcovr 7.x — full encoded path match (highest confidence)
    for f in html_files:
        if f.stem.endswith(encoded_full):
            return f.name

    # Pass 2: gcovr 8.x — basename match after stripping md5 hash suffix
    for f in html_files:
        stem_no_hash = _HASH_SUFFIX_RE.sub("", f.stem)
        if stem_no_hash.endswith(f".{encoded_base}"):
            return f.name

    return None


def generate_coverage_markdown(
    json_path: Path,
    output_path: Path,
    html_dir: Path | None = None,
    html_link_prefix: str = "coverage",
    heading: str = "Code Coverage",
) -> None:
    """Generate a Markdown coverage table from a gcovr JSON file."""
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    is_summary = "gcovr/summary_format_version" in data
    files = data.get("files", [])

    rows: list[tuple[str, int, int, float, int, int, int, int]] = []
    total_lines = 0
    total_covered = 0
    total_branches = 0
    total_branches_covered = 0
    total_conditions = 0
    total_conditions_covered = 0
    has_branches = False
    has_conditions = False

    for finfo in sorted(files, key=lambda f: f.get("filename", f.get("file", ""))):
        fname: str = finfo.get("filename", finfo.get("file", "unknown"))

        if is_summary:
            line_total = finfo.get("line_total", 0)
            line_covered = finfo.get("line_covered", 0)
            branch_total = finfo.get("branch_total", 0)
            branch_covered = finfo.get("branch_covered", 0)
            condition_total = finfo.get("condition_total", 0)
            condition_covered = finfo.get("condition_covered", 0)
        else:
            line_covered, line_total = _compute_line_coverage_from_trace(finfo)
            branch_covered, branch_total = _compute_branch_coverage_from_trace(finfo)
            condition_covered, condition_total = _compute_condition_coverage_from_trace(finfo)

        if branch_total > 0:
            has_branches = True
        if condition_total > 0:
            has_conditions = True

        line_pct = (line_covered / line_total * 100) if line_total > 0 else 0.0

        total_lines += line_total
        total_covered += line_covered
        total_branches += branch_total
        total_branches_covered += branch_covered
        total_conditions += condition_total
        total_conditions_covered += condition_covered

        display = f"`{fname}`"
        if html_dir:
            detail = _find_detail_file(html_dir, fname)
            if detail:
                # Use raw HTML link to prevent MyST from converting the .html
                # path into a Sphinx cross-reference (which adds a '#' prefix).
                link = f"{html_link_prefix}/{detail}"
                display = f'<a href="{link}"><code>{fname}</code></a>'

        rows.append((display, line_total, line_covered, line_pct, branch_covered, branch_total, condition_covered, condition_total))

    # Build output
    output_lines: list[str] = []
    if heading:
        output_lines.append(f"# {heading}")
        output_lines.append("")

    if has_branches:
        if has_conditions:
            output_lines.append("| File | Lines | Line % | Branches | Branch % | Conditions | Condition % |")
            output_lines.append("|------|------:|-------:|---------:|---------:|-----------:|------------:|")
        else:
            output_lines.append("| File | Lines | Line % | Branches | Branch % |")
            output_lines.append("|------|------:|-------:|---------:|---------:|")
    else:
        output_lines.append("| File | Lines | Coverage |")
        output_lines.append("|------|------:|---------:|")

    for display, lt, lc, lp, bc, bt, cc, ct in rows:
        row = f"| {display} | {lc}/{lt} | {lp:.1f}%"
        if has_branches:
            bp = (bc / bt * 100) if bt > 0 else 0.0
            row += f" | {bc}/{bt} | {bp:.1f}%"
            if has_conditions:
                cp = (cc / ct * 100) if ct > 0 else 0.0
                row += f" | {cc}/{ct} | {cp:.1f}%"
        output_lines.append(row + " |")

    total_pct = (total_covered / total_lines * 100) if total_lines > 0 else 0.0
    total_row = f"| **TOTAL** | **{total_covered}/{total_lines}** | **{total_pct:.1f}%**"
    if has_branches:
        total_bp = (total_branches_covered / total_branches * 100) if total_branches > 0 else 0.0
        total_row += f" | **{total_branches_covered}/{total_branches}** | **{total_bp:.1f}%**"
        if has_conditions:
            total_cp = (total_conditions_covered / total_conditions * 100) if total_conditions > 0 else 0.0
            total_row += f" | **{total_conditions_covered}/{total_conditions}** | **{total_cp:.1f}%**"
    total_row += " |"
    output_lines.append(total_row)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Markdown coverage table from gcovr JSON")
    parser.add_argument("--json", required=True, type=Path, help="Path to gcovr JSON file (trace or summary format)")
    parser.add_argument("--output", required=True, type=Path, help="Output Markdown file path")
    parser.add_argument("--html-dir", type=Path, default=None, help="Directory containing gcovr HTML detail files for per-file linking")
    parser.add_argument("--html-link-prefix", default="coverage", help="Relative URL prefix for HTML detail links (default: coverage)")
    parser.add_argument("--heading", default="Code Coverage", help="Heading for the Markdown page (default: Code Coverage)")
    args = parser.parse_args()
    generate_coverage_markdown(args.json, args.output, args.html_dir, args.html_link_prefix, args.heading)


if __name__ == "__main__":
    main()
