name: CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

    workflow_dispatch:
        inputs:
            target_branch:
                description: "The branch to release from"
                required: true
                default: "develop"

            prerelease_token:
                description:
                    "The prerelease token can be used when multiple users want to create release candidates.
                    One can define an own unique token to avoid conflicts: rcN.dev, where N is a digit. For example: rc1.dev"
                required: false
                default: "rc"

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    lint:
        name: Check (Lint) Commit Messages and Files
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Install pypeline runner
              run: pip install pypeline-runner>=1.23
              shell: bash

            - name: Run pypeline
              run: pypeline run --step PreCommit
              shell: bash

            # Make sure commit messages follow the conventional commits convention:
            # https://www.conventionalcommits.org
            - uses: wagoid/commitlint-github-action@v5

    test:
        name: Run Tests
        runs-on: windows-latest
        needs:
            - lint
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v6

            - name: install tools, build and test
              run: |
                  .\build.ps1
              shell: powershell

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action/windows@v2
              if: always()
              with:
                  files: |
                      out/test-report.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              if: always()
              with:
                  files: out/coverage.xml
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload test results to Codecov
              uses: codecov/codecov-action@v5
              if: always()
              with:
                  files: out/test-report.xml
                  report_type: test_results
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}

    release:
        needs:
            - test
            - lint

        runs-on: ubuntu-24.04
        environment: release
        concurrency: release
        permissions:
            id-token: write
            contents: write

        steps:
            - name: Generate Release Bot Token
              id: app-token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.inputs.target_branch || github.head_ref || github.ref_name }}
                  token: ${{ steps.app-token.outputs.token }}

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Determine Release Type
              id: determine_release
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                      echo "semantic_release_root_options=" >> $GITHUB_ENV
                      echo "prerelease=true" >> $GITHUB_ENV
                      echo "publish_release=true" >> $GITHUB_ENV
                  elif [ "${{ github.ref_name }}" = "develop" ]; then
                      echo "semantic_release_root_options=" >> $GITHUB_ENV
                      echo "prerelease=false" >> $GITHUB_ENV
                      echo "publish_release=true" >> $GITHUB_ENV
                  else
                      echo "semantic_release_root_options=--noop" >> $GITHUB_ENV
                      echo "prerelease=false" >> $GITHUB_ENV
                      echo "publish_release=false" >> $GITHUB_ENV
                  fi

            - name: Release
              uses: python-semantic-release/python-semantic-release@v9.16.1
              id: release
              with:
                  root_options: ${{ env.semantic_release_root_options }}
                  prerelease_token: ${{ github.event.inputs.prerelease_token }}
                  prerelease: ${{ env.prerelease }}
                  github_token: ${{ steps.app-token.outputs.token }}

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: env.publish_release == 'true' && steps.release.outputs.released == 'true'

            - name: Publish package distributions to GitHub Releases
              uses: python-semantic-release/publish-action@v9
              if: env.publish_release == 'true' && steps.release.outputs.released == 'true'
              with:
                  github_token: ${{ steps.app-token.outputs.token }}
