name: selftests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

env:
  # Workaround to avoid usage of system wide installations
  USER_PATH_FIRST: true


jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install tools and run selftests
        run: |
          .\build.ps1
        shell: powershell
