name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

env:
  # Workaround to avoid usage of system wide installations
  USER_PATH_FIRST: true

jobs:
  test:
    name: CI Gate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install tools and run selftests
        run: |
          .\build.ps1 -install
          .\build.ps1
        shell: powershell
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            out/test-report.xml
